window.VELVET_DATA={
profiles:[
{id:'aurelie-francois',name:'Aurélie & François',type:'Couple',ages:'38 & 41 ans',city:'Lille',distance:'8 km',compatibility:93,trust:91,verified:['Identités','Couple','Téléphone'],mood:'Complices, chaleureux, occasionnels',story:'Ensemble depuis quatorze ans, nous avançons dans cet univers avec douceur et curiosité. Nous aimons les échanges naturels, les belles tables et les soirées où l’on peut réellement discuter avant de laisser le feeling décider.',looking:['Couples complices','Femme seule','Soirées privées'],rhythm:'Une à deux sorties par mois',availability:['Vendredi soir','Samedi soir','Week-ends sans enfants'],practices:['Mélangisme','Côte-à-côtisme','Trios F','Clubs','Soirées privées'],curious:['Voyages libertins','Spa privatisé'],limits:['Aucune pression','Pas de brutalité','Préservatif systématique','Visage avant rencontre'],personality:['Bienveillants','Sensuels','Discrets','Spontanés'],albums:[['Moments à deux',8,'public'],['Élégance privée',12,'private'],['Ce week-end',4,'temporary']],recommendations:['Deux rencontres confirmées','Recommandés pour leur respect et leur ponctualité'],timeline:['Juin · Soirée privée à Lille','Mai · Première visite à O’Pulsions','Avril · Dîner Velvet à Arras'],bio:'Le feeling d’abord, toujours. Nous préférons une belle connexion à dix conversations sans profondeur.'},
{id:'claire',name:'Claire',type:'Femme seule',ages:'36 ans',city:'Arras',distance:'19 km',compatibility:89,trust:87,verified:['Identité','Téléphone'],mood:'Curieuse, élégante, indépendante',story:'Je découvre cet univers depuis deux ans. J’aime les couples stables, les attentions simples et les personnes qui savent écouter sans se mettre en scène.',looking:['Couples amoureux','Femmes bi-curieuses'],rhythm:'Une sortie par mois',availability:['Samedi soir','Dimanche après-midi'],practices:['Trios','Spa','Mélangisme'],curious:['Week-end confidentiel'],limits:['Pas d’hommes seuls','Pas de photos sans accord','Pas de rencontre improvisée'],personality:['Sensible','Cultivée','Joueuse','Posée'],albums:[['Portraits',6,'public'],['Instants privés',9,'private']],recommendations:['Profil confirmé par 3 couples'],timeline:['Juillet · Spa à Lille','Mai · Soirée privée à Béthune'],bio:'J’aime quand la conversation devient déjà une expérience en soi.'},
{id:'elodie-marc',name:'Élodie & Marc',type:'Couple',ages:'42 & 44 ans',city:'Béthune',distance:'28 km',compatibility:86,trust:94,verified:['Identités','Couple','Téléphone','Rencontre'],mood:'Épicuriens, expérimentés, accueillants',story:'Nous fréquentons les clubs depuis plusieurs années, sans course au tableau de chasse. Nous aimons guider les nouveaux venus, recevoir autour d’un bon dîner et découvrir des lieux soignés.',looking:['Couples','Femme seule','Amis de sorties'],rhythm:'Deux sorties par mois',availability:['Jeudi','Vendredi','Samedi'],practices:['Échangisme','Mélangisme','Clubs','Réceptions privées'],curious:['Séjour au Cap'],limits:['Hygiène irréprochable','Respect du couple','Non-fumeurs'],personality:['Sociables','Rassurants','Festifs','Directs'],albums:[['Notre univers',11,'public'],['Après minuit',16,'private']],recommendations:['8 rencontres confirmées','Ambassadeurs locaux'],timeline:['Juillet · L’Eden Lille','Juin · La Tentation','Mai · Garden party privée'],bio:'Nous aimons les gens simples, élégants et capables de rire.'},
{id:'lea-thomas',name:'Léa & Thomas',type:'Couple',ages:'31 & 34 ans',city:'Lens',distance:'34 km',compatibility:84,trust:82,verified:['Identités','Couple'],mood:'Nouveaux, soudés, très sélectifs',story:'Inscrits depuis quelques semaines, nous voulons découvrir sans brûler les étapes. Un verre, une discussion et aucune obligation.',looking:['Couples débutants','Sorties conviviales'],rhythm:'Occasionnel',availability:['Samedi soir'],practices:['Côte-à-côtisme','Exhibition légère'],curious:['Club','Spa'],limits:['Pas de séparation','Pas d’hommes seuls','Pas de messages insistants'],personality:['Timides','Tendres','Curieux'],albums:[['Nous deux',5,'public'],['À découvrir',7,'private']],recommendations:['Profil couple vérifié'],timeline:['Juillet · Inscription Velvet'],bio:'Nous cherchons une première expérience rassurante, pas une performance.'},
{id:'sophie-nicolas',name:'Sophie & Nicolas',type:'Couple',ages:'46 & 48 ans',city:'Valenciennes',distance:'62 km',compatibility:81,trust:96,verified:['Identités','Couple','Téléphone','Rencontres'],mood:'Raffinés, réguliers, voyageurs',story:'Notre liberté se construit depuis dix ans autour de voyages, de beaux hôtels et de rencontres suivies. Nous privilégions la qualité, l’humour et une vraie culture du consentement.',looking:['Couples suivis','Voyages','Dîners privés'],rhythm:'Deux week-ends par mois',availability:['Week-ends','Vacances scolaires'],practices:['Échangisme','Voyages','Clubs premium'],curious:['Croisière privée'],limits:['Discrétion absolue','Profils complets uniquement'],personality:['Élégants','Curieux','Exigeants'],albums:[['Escapades',14,'public'],['Confidentiel',20,'private']],recommendations:['12 rencontres confirmées','Trust Index exceptionnel'],timeline:['Juin · Bruxelles','Mai · Côte d’Opale','Mars · Paris'],bio:'Le luxe, pour nous, c’est le temps accordé à une belle rencontre.'},
{id:'marion-julie',name:'Marion & Julie',type:'Couple de femmes',ages:'33 & 35 ans',city:'Douai',distance:'38 km',compatibility:88,trust:89,verified:['Identités','Couple','Téléphone'],mood:'Douces, créatives, ouvertes',story:'Nous aimons les univers artistiques, les soirées intimistes et les personnes qui ne cherchent pas à nous enfermer dans une catégorie.',looking:['Femmes','Couples respectueux'],rhythm:'Une sortie par mois',availability:['Vendredi','Samedi'],practices:['Trios','Mélangisme','Soirées privées'],curious:['Voyage entre femmes'],limits:['Pas de fétichisation','Pas d’hommes seuls'],personality:['Créatives','Tendres','Drôles'],albums:[['Lumières',9,'public'],['Backstage',10,'private']],recommendations:['Recommandées par 4 membres'],timeline:['Juillet · Dîner à Lille','Avril · Spa privé'],bio:'Nous aimons les regards qui prennent le temps.'}
],
venues:[
{id:'opulsions',name:'O’Pulsions',city:'Hénin-Beaumont',type:'Club libertin',summary:'Un vaste club régional sur deux niveaux, pensé pour la fête, la rencontre et la découverte.',facts:['Plus de 500 m² annoncés','Vendredi, samedi et dimanche selon programmation','Couples, femmes, hommes et personnes trans accueillis selon les soirées'],note:'Fiche de démonstration inspirée des informations publiques de l’établissement. Velvet n’est pas affilié au lieu.'},
{id:'tentation',name:'La Tentation',city:'Prémesques',type:'Discothèque érotique',summary:'Une adresse historique de la métropole lilloise, orientée ambiance club, thèmes et musique électro-house.',facts:['Soirées le vendredi et le samedi','Dress code élégant','Téléphones et photos interdits dans l’établissement'],note:'Fiche de démonstration inspirée des informations publiques de l’établissement. Velvet n’est pas affilié au lieu.'},
{id:'eden',name:'L’Eden',city:'Lille',type:'Spa libertin',summary:'Un espace bien-être en cœur de ville avec spa, hammam, sauna sec et soirées couples ou mixtes.',facts:['Jeudi soir annoncé 100 % couples et femmes seules','Autres jours mixtes selon programmation','Accent public mis sur l’hygiène et les espaces bien-être'],note:'Fiche de démonstration inspirée des informations publiques de l’établissement. Velvet n’est pas affilié au lieu.'},
{id:'orelax',name:'O’Relax',city:'Lens',type:'Spa libertin',summary:'Un spa libertin lensois consacré à la relaxation, aux rencontres et aux événements thématiques.',facts:['Spa à Lens','Espaces de détente et de jeux','Programmation événementielle variable'],note:'Fiche de démonstration inspirée des informations publiques de l’établissement. Velvet n’est pas affilié au lieu.'}
],
events:[
{id:'e1',title:'Premiers pas, sans pression',date:'Vendredi 7 août · 20h30',place:'Salon privé · Lille',host:'Équipe Velvet',attendees:18,description:'Un apéritif en petit comité pour découvrir les codes, poser ses questions et rencontrer sans obligation.'},
{id:'e2',title:'Nuit velours',date:'Samedi 15 août · 21h30',place:'O’Pulsions · Hénin-Beaumont',host:'Événement démo',attendees:42,description:'Une sortie communautaire fictive pour tester les inscriptions, le covoiturage et la visibilité des participants.'},
{id:'e3',title:'Parenthèse bien-être',date:'Dimanche 23 août · 14h00',place:'O’Relax · Lens',host:'Événement démo',attendees:16,description:'Après-midi détente fictive avec jauge limitée et participants visibles uniquement après validation.'}
],
messages:[
{name:'Aurélie & François',time:'09:42',text:'Votre façon de voir les choses nous parle beaucoup. Vous sortez parfois sur Lille ?'},
{name:'Claire',time:'Hier',text:'Merci pour l’ouverture de votre album. Vos photos sont très élégantes.'},
{name:'Élodie & Marc',time:'Lundi',text:'Nous serons à La Tentation le mois prochain, peut-être l’occasion de prendre un verre.'}
]
};