begin;

create table if not exists public.pro_social_connections (
  id uuid primary key default gen_random_uuid(),
  establishment_id uuid not null references public.establishments(id) on delete cascade,
  provider text not null check (provider in ('meta','tiktok')),
  provider_account_id text,
  provider_account_name text,
  provider_account_handle text,
  credentials_ciphertext text,
  granted_scopes text[] not null default '{}',
  status text not null default 'pending' check (status in ('pending','selection_required','active','expired','revoked','error')),
  expires_at timestamptz,
  last_verified_at timestamptz,
  configuration jsonb not null default '{}'::jsonb,
  last_error text,
  connected_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (establishment_id, provider)
);

create index if not exists pro_social_connections_establishment_idx
  on public.pro_social_connections(establishment_id, provider, status);

create table if not exists public.pro_marketing_campaigns (
  id uuid primary key default gen_random_uuid(),
  establishment_id uuid not null references public.establishments(id) on delete cascade,
  event_id uuid references public.events(id) on delete set null,
  studio_project_id uuid references public.pro_studio_projects(id) on delete set null,
  studio_render_id uuid references public.pro_studio_renders(id) on delete set null,
  title text not null,
  objective text not null default 'event_registration',
  status text not null default 'draft' check (status in ('draft','ready','scheduled','running','completed','cancelled','archived')),
  base_copy text not null default '',
  call_to_action text not null default '',
  landing_url text,
  selected_networks text[] not null default '{}',
  editorial_plan jsonb not null default '[]'::jsonb,
  compliance_report jsonb not null default '{}'::jsonb,
  settings jsonb not null default '{}'::jsonb,
  approved_at timestamptz,
  approved_by uuid references auth.users(id) on delete set null,
  created_by uuid not null references auth.users(id) on delete restrict,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pro_marketing_campaigns_establishment_updated_idx
  on public.pro_marketing_campaigns(establishment_id, updated_at desc);
create index if not exists pro_marketing_campaigns_event_idx
  on public.pro_marketing_campaigns(event_id, status);

create table if not exists public.pro_marketing_publications (
  id uuid primary key default gen_random_uuid(),
  establishment_id uuid not null references public.establishments(id) on delete cascade,
  campaign_id uuid not null references public.pro_marketing_campaigns(id) on delete cascade,
  connection_id uuid references public.pro_social_connections(id) on delete set null,
  provider text not null check (provider in ('facebook','instagram','tiktok')),
  publication_kind text not null default 'feed' check (publication_kind in ('feed','story','reel','photo','video','draft')),
  sequence_code text not null default 'primary',
  copy text not null default '',
  media_render_id uuid references public.pro_studio_renders(id) on delete set null,
  scheduled_at timestamptz not null,
  status text not null default 'scheduled' check (status in ('draft','scheduled','processing','published','draft_delivered','failed','cancelled')),
  settings jsonb not null default '{}'::jsonb,
  external_post_id text,
  external_post_url text,
  external_publish_id text,
  attempts integer not null default 0 check (attempts between 0 and 20),
  last_attempt_at timestamptz,
  published_at timestamptz,
  error_code text,
  error_message text,
  metrics jsonb not null default '{}'::jsonb,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (campaign_id, provider, sequence_code)
);

create index if not exists pro_marketing_publications_due_idx
  on public.pro_marketing_publications(status, scheduled_at)
  where status = 'scheduled';
create index if not exists pro_marketing_publications_campaign_idx
  on public.pro_marketing_publications(campaign_id, scheduled_at asc);

create table if not exists public.pro_marketing_metrics (
  id bigint generated by default as identity primary key,
  establishment_id uuid not null references public.establishments(id) on delete cascade,
  publication_id uuid not null references public.pro_marketing_publications(id) on delete cascade,
  provider text not null check (provider in ('facebook','instagram','tiktok')),
  captured_at timestamptz not null default now(),
  impressions integer,
  reach integer,
  views integer,
  likes integer,
  comments integer,
  shares integer,
  saves integer,
  clicks integer,
  registrations integer,
  payload jsonb not null default '{}'::jsonb
);

create index if not exists pro_marketing_metrics_publication_captured_idx
  on public.pro_marketing_metrics(publication_id, captured_at desc);

create table if not exists public.pro_marketing_audit_log (
  id bigint generated by default as identity primary key,
  establishment_id uuid not null references public.establishments(id) on delete cascade,
  campaign_id uuid references public.pro_marketing_campaigns(id) on delete set null,
  publication_id uuid references public.pro_marketing_publications(id) on delete set null,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists pro_marketing_audit_establishment_idx
  on public.pro_marketing_audit_log(establishment_id, created_at desc);

create or replace function public.pro_marketing_touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists pro_social_connections_touch on public.pro_social_connections;
create trigger pro_social_connections_touch
before update on public.pro_social_connections
for each row execute function public.pro_marketing_touch_updated_at();

drop trigger if exists pro_marketing_campaigns_touch on public.pro_marketing_campaigns;
create trigger pro_marketing_campaigns_touch
before update on public.pro_marketing_campaigns
for each row execute function public.pro_marketing_touch_updated_at();

drop trigger if exists pro_marketing_publications_touch on public.pro_marketing_publications;
create trigger pro_marketing_publications_touch
before update on public.pro_marketing_publications
for each row execute function public.pro_marketing_touch_updated_at();

alter table public.pro_social_connections enable row level security;
alter table public.pro_marketing_campaigns enable row level security;
alter table public.pro_marketing_publications enable row level security;
alter table public.pro_marketing_metrics enable row level security;
alter table public.pro_marketing_audit_log enable row level security;

create policy pro_social_connections_select on public.pro_social_connections
for select to authenticated using (public.can_manage_pro_studio(establishment_id));
create policy pro_social_connections_write on public.pro_social_connections
for all to authenticated using (public.can_manage_pro_studio(establishment_id))
with check (public.can_manage_pro_studio(establishment_id));

create policy pro_marketing_campaigns_select on public.pro_marketing_campaigns
for select to authenticated using (public.can_manage_pro_studio(establishment_id));
create policy pro_marketing_campaigns_write on public.pro_marketing_campaigns
for all to authenticated using (public.can_manage_pro_studio(establishment_id))
with check (public.can_manage_pro_studio(establishment_id));

create policy pro_marketing_publications_select on public.pro_marketing_publications
for select to authenticated using (public.can_manage_pro_studio(establishment_id));
create policy pro_marketing_publications_write on public.pro_marketing_publications
for all to authenticated using (public.can_manage_pro_studio(establishment_id))
with check (public.can_manage_pro_studio(establishment_id));

create policy pro_marketing_metrics_select on public.pro_marketing_metrics
for select to authenticated using (public.can_manage_pro_studio(establishment_id));
create policy pro_marketing_metrics_write on public.pro_marketing_metrics
for all to authenticated using (public.can_manage_pro_studio(establishment_id))
with check (public.can_manage_pro_studio(establishment_id));

create policy pro_marketing_audit_select on public.pro_marketing_audit_log
for select to authenticated using (public.can_manage_pro_studio(establishment_id));
create policy pro_marketing_audit_insert on public.pro_marketing_audit_log
for insert to authenticated with check (public.can_manage_pro_studio(establishment_id));

commit;
